### ISSUE TITLE
HTTP 500 error in notifications API when unauthenticated

### ISSUE THREAD

**Issue by thsutton** [aristotle-mdr/aristotle-metadata-registry#335] opened 2016-02-08 02:09 UTC
The notifications application attempts to load the user's notifications from `/account/notifications/api/unread_list/` whether or not the user is authenticated. This results in an HTTP 500 error for unauthenticated users in my test instance and the pythonanywhere.com instance with the exception:

````
Exception Value: 'AnonymousUser' object has no attribute 'notifications'
````

You can see it on the demo server here http://aristotle.pythonanywhere.com/account/notifications/api/unread_list/?max=10 (assuming you are unauthenticated).

I'm not sure whether to blame Aristotle, notifications, django.contrib.auth.

**Comment by LegoStormtroopr** [comment] 2016-02-08 03:14
Probably blame Aristotle for this one. An unauthenticated user won't have notifications by design.

The best solutions is probably including some logic in `base.html` to prevent the notifications javascript from being loaded

**Comment by LegoStormtroopr** [comment] 2016-02-08 03:29
Actually, its both Aristotle *and* notifications. Fortunately, I'm a contributor over there too, and I've lodged a bug which I can take care of. For the mean time, I'll add some sentinel logic around the javascript to prevent this loading for unauthenticated users.

**Comment by LegoStormtroopr** [comment] 2016-02-08 04:30
@thsutton  I've  thrown up a PR that does some basic checking in the template to stop the offending javascript calling the invalid API. If an unauthenticated user browses to `/account/notifications/api/unread_list/` it will still spit up a 500 error.

There is an issue and PR raised in django-notifications to fix this properly.

Thoughts on closing this from PR #337 ?

**Comment by thsutton** [comment] 2016-02-08 04:40
Sounds good.

**Closed** 2016-02-08 10:10 UTC
Labels: bug
